[project]
org-name= "isurun"
version= "1.0.0"
license = ["Apache-2.0"]
authors = ["Isuru Nuwanthilaka"]
repository = "https://github.com/isurunuwanthilaka/ballerina-medium-connector"
keywords = ["ballerina", "medium", "connector", "integration"]
[dependencies]
